cd /ps_new/BiaoZhun
python main.py
cd /ps_new/crawler/news
python main.py
cd /ps_new/crawler/park_news
python main.py
cd /ps_new/spy
python zhence.py
cd /ps_new/spy
python zhence2.py
cd /ps_new/spy/ShangHaiOne
python main.py